linters:
  enable:
    # Default linters plus these:
    - contextcheck # [-] Checks whether the function uses a non-inherited context
    - exhaustive # [+] Checks exhaustiveness of enum switch statements
    - exportloopref # [-] Checks for pointers to enclosing loop variables
    - gci # [+] Checks package import order and makes it always deterministic
    - goconst # [+] Checks for repeated strings that could be replaced by a constant
    - gofmt # [+] Checks whether code was gofmt-ed
    - mnd # [+] Checks for magic numbers
    - nilerr # [+] Finds the code that returns nil even if it checks that the error is not nil
    - perfsprint # [+] Checks for fmt.Sprintf calls, that can be replaced with a faster alternative
    - prealloc # [+] Checks for slice declarations that could potentially be pre-allocated
    - testifylint # [+] Checks usage of github.com/stretchr/testify
    - thelper # [+] Checks for test helpers which do not start with t.Helper()
    - unconvert # [+] Checks for unnecessary type conversions 
    - paralleltest # [+] Check for t.Parallel() calls
    - revive # [+] Metalinter
linters-settings:
  exhaustive:
    check:
      - switch
    default-signifies-exhaustive: true
    default-case-required: true
  goconst:
    ignore-tests: true
    ignore-calls: false
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      # - assign # triggers for fields like: `statusCode: 200`
  prealloc:
    simple: false
    range-loops: true
    for-loops: true
  testifylint:
    enable-all: true
  revive:
    ignore-generated-header: true
    severity: warning
    enable-all-rules: true
    confidence: 0.8
    # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    rules:
      - name: add-constant
        disabled: true # goconst does it better
      - name: line-length-limit
        severity: warning
        arguments: [100]
      - name: function-length
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: line-length-limit
        disabled: true
run:
  timeout: 3m
  tests: true
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: true
